### ISSUE TITLE
PKUNLP link expired

### ISSUE THREAD

**Issue by MichaelCaohn** [wang136906578/ChineseGEC#1]
Hi authors,

Thank you very much for the greater work.

I just discovered that the link you provided to PKUNLP has experied. Therefore, can you provide a new link for it?

Thank you

**Comment by liangjinggui** [comment]
> Hi authors,
> 
> Thank you very much for the greater work.
> 
> I just discovered that the link you provided to PKUNLP has experied. Therefore, can you provide a new link for it?
> 
> Thank you

Hi, I am also looking for the pkunlp segment tool. Have you found it yet？if yes，can you provide a new link for it or send it to me by email？Thank you very much！！！

**Comment by wang136906578** [comment]
@liangjinggui I had a previously saved one and uploaded it to Google Drive. https://drive.google.com/file/d/17OKIqbS74_GATm65Yg-JowqXZsVk84-W/view?usp=sharing

**Comment by liangjinggui** [comment]
> @liangjinggui I had a previously saved one and uploaded it to Google Drive. https://drive.google.com/file/d/17OKIqbS74_GATm65Yg-JowqXZsVk84-W/view?usp=sharing

Thank you very much!
